version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:
